name: Test versioning

on:
  push:
    branches: [ "xxx" ]
  pull_request:
    branches: [ "xxx" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Export environment variables'
        run: |
          echo "VERSION_NAME=$(cat app/build/outputs/app_versioning/prodRelease/version_name.txt)"
          echo "VERSION_CODE=$(cat app/build/outputs/app_versioning/prodRelease/version_code.txt)"