name: Test versioning

on:
  push:
    branches: [ "xxx" ]
  pull_request:
    branches: [ "xxx" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode BASEURL
        env:
          APIKEY: ${{ secrets.API_KEY_GH }}
        run: echo YOUR_API_KEY="$APIKEY" > ./local.properties

      - name: Build with Gradle
        run: ./gradlew build

      - name: 'Export environment variables'
        run: |
          echo "VERSION_NAME=$(cat app/build/outputs/app_versioning/debug/version_name.txt)"
          echo "VERSION_CODE=$(cat app/build/outputs/app_versioning/debug/version_code.txt)"